apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-service
  labels:
    app: result-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
      - name: result-service
        image: ${REGISTRY}/pollpulse/result-service:${TAG}
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: pollpulse-config
              key: postgres-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: pollpulse-config
              key: postgres-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pollpulse-secrets
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pollpulse-secrets
              key: postgres-password
        - name: DB_NAME
          value: "pollpulse_results"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pollpulse-secrets
              key: jwt-secret
        - name: USER_SERVICE_URL
          value: "http://user-service:8081"
        - name: SURVEY_SERVICE_URL
          value: "http://survey-service:8082"
        - name: LOG_LEVEL
          value: "info"
        - name: ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP 