apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-service
  labels:
    app: survey-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survey-service
  template:
    metadata:
      labels:
        app: survey-service
    spec:
      containers:
      - name: survey-service
        image: ${REGISTRY}/pollpulse/survey-service:${TAG}
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: pollpulse-config
              key: postgres-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: pollpulse-config
              key: postgres-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pollpulse-secrets
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pollpulse-secrets
              key: postgres-password
        - name: DB_NAME
          value: "pollpulse_surveys"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pollpulse-secrets
              key: jwt-secret
        - name: USER_SERVICE_URL
          value: "http://user-service:8081"
        - name: LOG_LEVEL
          value: "info"
        - name: ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: survey-service
spec:
  selector:
    app: survey-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP 